[DEFAULT]
enabled: True
antibouncehack: False

[VolumeControl]
enabled: True
Type: TwoButtonControl
Pin1: 16
Pin2: 13
pull_up_down: pull_up
hold_time: 0.3
hold_mode: Repeat
functionCall1: functionCallVolU
functionCall2: functionCallVolD
functionCallTwoButtons: functionCallVol0
;functionCall1Args: 1
;functionCall2Args: 1
;functionCallTwoButtonsArgs: x

[PrevNextControl]
enabled: True
Type: TwoButtonControl
Pin1: 27
Pin2: 26
functionCall1: functionCallPlayerPrev
functionCall2: functionCallPlayerNext
functionCallTwoButtons: None
pull_up_down: pull_up
hold_time: 0.3
hold_mode: None

[PlayPause]
enabled: True
Type: Button
Pin: 12
pull_up_down: pull_up
functionCall: functionCallPlayerPause

